
TABLE_LENGTH_Y: 2.0
TABLE_LENGTH_X: 3.0
TABLE_LENGTH_Z: 0.5

CAMERA_WIDTH: 2448.
CAMERA_HEIGHT: 2048.
HOMO_IMAGE_SCALE: 2.
HOMO_IMAGE_WIDTH: CAMERA_WIDTH/HOMO_IMAGE_SCALE
HOMO_IMAGE_HEIGHT: CAMERA_HEIGHT/HOMO_IMAGE_SCALE

CAMERA_X:  1.5
CAMERA_Y:  0.0
CAMERA_Z:  1.0
CAMERA_ANGLE:  [2.255, 0, 0]

PUCK_RADIUS: 0.038
pixel_scale_x: CAMERA_WIDTH/TABLE_LENGTH_X
pixel_scale_y: CAMERA_HEIGHT/TABLE_LENGTH_Y
PUCK_RADIUS_pixel_x: pixel_scale_x*PUCK_RADIUS
PUCK_RADIUS_pixel_y: pixel_scale_y*PUCK_RADIUS

MAX_FEATURES: 10000
GOOD_MATCH_PERCENT: 0.1

REDIUM_COLOR:  [230, 0, 0]
GREENIUM_COLOR:  [77, 255, 25]
BLUEIUM_COLOR:  [25, 153, 255]

LAB_REDIUM: [48.04335752, 74.08054268, 62.1584816 ]
LAB_GREENIUM: [88.52609404, -79.01588508, 81.76924998]
LAB_BLUEIUM: [61.83055688, 4.32627342, -59.4598142]
