secondary_robot:
  purple_side:
    first_puck_zone: [0.225, 1.8, 1.57]
    second_puck_zone: [0.125, 1.8, 1.57]
    third_puck_zone: [0.6, 1.34, 1.57]
    forth_puck_zone: [0.8, 1.34, 1.57]
    fifth_puck_zone: [1.0, 1.34, 1.57]
    scales_zone: [1.34, 1.47, 3.65]
    sixth_puck_zone: [0.9, 1.34, 1.57]
    seventh_puck_zone: [0.7, 1.34, 1.57]
    eighth_puck_zone: [0.5, 1.34, 1.57]
    nineth_puck_zone: [0.325, 1.8, 1.57]
    start_zone: [0.23, 0.84, 0]
    redium_zone_first: [0.15, 0.5, -1.57]
    redium_zone_second: [0.25, 0.5, -1.57]
    redium_zone_third: [0.25, 0.6, -1.57]
    redium_zone_forth: [0.15, 0.6, -1.57]


  yellow_side:
    first_puck_zone: [2.775, 1.8, 1.57]
    second_puck_zone: [2.875, 1.8, 1.57]
    third_puck_zone: [2.4, 1.34, 1.57]
    forth_puck_zone: [2.2, 1.34, 1.57]
    fifth_puck_zone: [2.0, 1.34, 1.57]
    scales_zone: [1.66, 1.48, 3.65]
    sixth_puck_zone: [2.1, 1.34, 1.57]
    seventh_puck_zone: [2.3, 1.34, 1.57]
    eighth_puck_zone: [2.5,  1.34, 1.57]
    nineth_puck_zone: [2.675, 1.8, 1.57]
    start_zone: [2.77, 0.84, 3.14]
    redium_zone_first: [2.85, 0.5, -1.57]
    redium_zone_second: [2.75, 0.5, -1.57]
    redium_zone_third: [2.75, 0.6, -1.5]
    redium_zone_forth: [2.85, 0.6, -1.57]



#FIXME::CHANGE ZONE TO SIDE
# Main robot
yellow_zone:
  start_zone: [2.6, 0.45, -1.57]

  red_cell_puck: [2.5, 0.45]
  green_cell_puck: [2.5, 0.75]
  blue_cell_puck: [2.5, 1.05]

  scales_area: [[1.4, 1], [1.4, 1.6], [2.3, 1.], [2.3, 1.6]]
  # blunium_collect_PREpos: [1.275, 0.35, -1.57]
  # blunium_collect_pos: [1.29, 0.24, -1.57]

  # blunium_rotate_PREpose: [1.295, 0.235, -0.78]
  # blunium_rotate_pose: [1.295, 0.235, -1.57]

  blunium_push_PREpose: [1.40, 0.165, 0.56]
  blunium_push_pose: [1.07, 0.165, 0.56]

  # accelerator_PREunloading_pos: [1.12, 0.165, 0.56]  # 0.525
  # accelerator_unloading_pos_far: [1.06, 0.15, 0.56]
  # accelerator_unloading_pos: [1.06, 0.135, 0.56]
  # chaos_push_pose: []
  # chaos_in_red_zone: []

  goldenium_first_PREgrab_pos: [1.11, 0.25, 0.56]
  goldenium_second_PREgrab_pos: [0.78, 0.35, -1.57]
  goldenium_grab_pos: [0.775, 0.27, -1.57]

  scales_goldenium_PREpos: [1.8, 0.6, 1.4]
  scales_goldenium_pos: [1.72, 1.4, 1.9]

#FIXME::CHANGE ZONE TO SIDE
# can be reached using rospy.get_param("purple_zone/red_cell_puck"
purple_zone:
  start_zone: [0.4, 0.45, 0]

  red_cell_puck: [0.5, 0.45]
  green_cell_puck: [0.5, 0.75]
  blue_cell_puck: [0.5, 1.05]
  
  scales_area: [[1.4, 1.2], [1.4, 1.6], [0.7, 1.2], [0.7, 1.6]]

  # blunium_collect_PREpos: [1.72, 0.45, -1.57]
  # blunium_collect_pos: [1.72, 0.25, -1.57]

  blunium_push_PREpose: [1.72, 0.165, 0.56]
  blunium_push_pose: [2.05, 0.165, 0.56]

  # accelerator_PREunloading_pos: [1.86, 0.2, 0.525]
  # accelerator_unloading_pos_far: [1.86, 0.16, 0.525]
  # accelerator_unloading_pos: [1.86, 0.125, 0.525]

  goldenium_first_PREgrab_pos: [2.01, 0.25, 0.56]
  goldenium_second_PREgrab_pos: [2.1, 0.35, -1.57]
  goldenium_grab_pos: [2.25, 0.27, -1.57]

  scales_goldenium_PREpos: [1.34, 0.6, 1.4]
  scales_goldenium_pos: [1.34, 1.2, 1.4]  # for main  # FIXME
