secondary_robot:
  purple_side:
    first_puck_zone: [0.225, 1.82, 1.57]
    second_puck_zone: [0.125, 1.82, 1.57]
    third_puck_zone: [0.595, 1.36, 1.57]
    forth_puck_zone: [0.795, 1.36, 1.57]
    fifth_puck_zone: [0.995, 1.36, 1.57]
    scales_zone: [1.35, 1.48, 3.65]
    sixth_puck_zone: [0.895, 1.36, 1.57]
    seventh_puck_zone: [0.695, 1.36, 1.57]
    eighth_puck_zone: [0.495, 1.36, 1.57]
    nineth_puck_zone: [0.325, 1.82, 1.57]
    start_zone: [0.2, 0.75, 0.]
    redium_zone_center: [0.275, 0.45, -1.57]
    redium_zone_first: [0.15, 0.65, -1.57]
    redium_zone_second: [0.25, 0.65, -1.57]
    redium_zone_third: [0.25, 0.75, -1.57]
    redium_zone_forth: [0.15, 0.75, -1.57]


  yellow_side:
    first_puck_zone: [2.77, 1.82, 1.57]
    second_puck_zone: [2.88, 1.82, 1.57]
    third_puck_zone: [2.4, 1.36, 1.57]
    forth_puck_zone: [2.2, 1.36, 1.57]
    fifth_puck_zone: [2.0, 1.36, 1.57]
    scales_zone: [1.66, 1.49, 3.65]
    sixth_puck_zone: [2.1, 1.36, 1.57]
    seventh_puck_zone: [2.3, 1.36, 1.57]
    eighth_puck_zone: [2.5,  1.36, 1.57]
    nineth_puck_zone: [2.675, 1.82, 1.57]
    start_zone: [2.80, 0.75, 3.14]
    redium_zone_center: [2.725, 0.45, -1.57]
    redium_zone_first: [2.85, 0.65, -1.57]
    redium_zone_second: [2.75, 0.65, -1.57]
    redium_zone_third: [2.75, 0.75, -1.5]
    redium_zone_forth: [2.85, 0.75, -1.57]


ground_spacing_dist: 0.3

# Main robot
yellow_side:
  red_cell_puck: [2.51, 0.45]
  blunium: [1.29, 0.025]  # outer side of the puck
  scales_area: [[1.4, 1], [1.4, 1.6], [2.3, 1.6], [2.3, 1.]]
  goldenium: [0.77, 0.05]  # outer side of the puck
  chaos_center: [2.01, 1.05]

purple_side:
  red_cell_puck: [0.5, 0.45]
  blunium: [1.71, 0.025]  # outer side of the puck
  scales_area: [[1.4, 1.2], [1.4, 1.6], [0.7, 1.6], [0.7, 1.2]]
  goldenium: [2.22, 0.05]  # outer side of the puck
  chaos_center: [1, 1.05]
