first_puck_zone_left: [0.12, 1.82, 1.57]
second_puck_zone_left: [0.21, 1.82, 1.57]
third_puck_zone_left: [0.59, 1.34, 1.57]
forth_puck_zone_left: [0.79, 1.34, 1.57]
fifth_puck_zone_left: [0.99, 1.34, 1.57]
scales_zone_left: [1.34, 1.34, 3.65]
start_zone_left: [0.23, 0.44, 0]


first_puck_zone_right: [2.88, 1.82, 1.5]
second_puck_zone_right: [2.78, 1.82, 1.5]
third_puck_zone_right: [2.41, 1.34, 1.5]
forth_puck_zone_right: [2.21, 1.34, 1.5]
fifth_puck_zone_right: [2.01, 1.34, 1.5]
scales_zone_right: [1.65, 1.34, 3.65]
start_zone_right: [2.53, 0.44, 3.14]

# Orange zone
# red_cell_puck: [2.5, 0.45]
# green_cell_puck: [2.5, 0.75]
# blue_cell_puck: [2.5, 1.05]

# Purple zone
red_cell_puck: [0.5, 0.45]
green_cell_puck: [0.5, 0.75]
blue_cell_puck: [0.5, 1.05]