first_puck_zone: [0.6, 1.34, 1.57]
second_puck_zone: [0.8, 1.34, 1.57]
third_puck_zone: [1, 1.34, 1.57]
forth_puck: [0.6, 1.34, 1.57]
fifth_puck: [0.6, 1.34, 1.57]

# Orange zone
# red_cell_puck: [2.5, 0.45]
# green_cell_puck: [2.5, 0.75]
# blue_cell_puck: [2.5, 1.05]
# blunium_start_push_pos: [1.24, 0.26, -1.57]  # for main
# blunium_finish_push_pos: [1.32, 0.26, -1.57]  # for main
# accelerator_unloading_pos: [1.15, 0.17, -1.57]  # for main
# goldenium_grab_pos: [0.775, 0.26, 4.71]  # for main
# scales_unloading_pos: [1.65, 1.48, 3.65]  # for secondary robot
# scales_goldenium_pos: [1.65, 1.4, 1.4]  # for main

# Purple zone
purple_zone:
  red_cell_puck: [0.5, 0.45]
  green_cell_puck: [0.5, 0.75]
  blue_cell_puck: [0.5, 1.05]
  blunium_start_push_pos: [1.8, 0.26, -1.57]  # for main
  blunium_finish_push_pos: [1.72, 0.26, -1.57]  # for main
  accelerator_unloading_pos: [1.85, 0.17, -1.57]  # for main
  goldenium_grab_pos: [2.25, 0.26, 4.71]  # for main
  scales_unloading_pos: [1.34, 1.48, 3.65]  # for secondary robot
  scales_goldenium_pos: [1.34, 1.4, 1.4]  # for main
