first_puck_zone_left: [0.12, 1.82, 1.57]
second_puck_zone_left: [0.21, 1.82, 1.57]
third_puck_zone_left: [0.585, 1.34, 1.57]
forth_puck_zone_left: [0.785, 1.34, 1.57]
fifth_puck_zone_left: [0.985, 1.34, 1.57]
scales_zone_left: [1.34, 1.34, 3.65]
start_zone_left: [0.23, 0.84, 0]


first_puck_zone_right: [2.88, 1.82, 1.57]
second_puck_zone_right: [2.79, 1.82, 1.57]
third_puck_zone_right: [2.415, 1.34, 1.57]
forth_puck_zone_right: [2.215, 1.34, 1.57]
fifth_puck_zone_right: [2.015, 1.34, 1.57]
scales_zone_right: [1.65, 1.34, 3.65]
start_zone_right: [2.77, 0.84, 3.14]


yellow_zone:
  start_zone: [2.82, 0.45, 3.14]
  red_cell_puck: [2.5, 0.45]
  green_cell_puck: [2.5, 0.75]
  blue_cell_puck: [2.5, 1.05]
  blunium_start_push_PREpos: [1.4, 0.4, -1.57]
  blunium_start_push_pos: [1.4, 0.25, -1.57]  # for main  # FIXME
  blunium_finish_push_pos: [1.29, 0.25, -1.57]  # for main
  accelerator_PREunloading_pos: [1.14, 0.2, 0.525]
  accelerator_unloading_pos_far: [1.11, 0.16, 0.525]
  accelerator_unloading_pos: [1.11, 0.125, 0.525]  # for main
  goldenium_PREgrab_pos: [0.9, 0.6, -1.57]
  goldenium_grab_pos: [0.78, 0.24, -1.57]  # for main
  scales_goldenium_PREpos: [1.8, 1.05, 1.4]  # for main
  scales_goldenium_pos: [1.72, 1.4, 1.9]  # for main

# can be reached using rospy.get_param("purple_zone/red_cell_puck"
purple_zone:
  start_zone: [0.28, 0.45, 0]
  red_cell_puck: [0.5, 0.45]
  green_cell_puck: [0.5, 0.75]
  blue_cell_puck: [0.5, 1.05]
  blunium_start_push_pos: [1.8, 0.26, -1.57]  # for main
  blunium_finish_push_pos: [1.72, 0.26, -1.57]  # for main
  accelerator_PREunloading_pos: [1.86, 0.2, 0.525]
  accelerator_unloading_pos_far: [1.86, 0.16, 0.525]
  accelerator_unloading_pos: [1.86, 0.125, 0.525]  # for main
  goldenium_PREgrab_pos: [2.1, 0.4, -1.57]
  goldenium_grab_pos: [2.25, 0.24, -1.57]  # for main
  scales_goldenium_PREpos: [1.34, 1.05, 1.4]  # for main
  scales_goldenium_pos: [1.34, 1.4, 1.4]  # for main  # FIXME
