first_puck_zone: [0.6, 1.34, 1.57]
second_puck_zone: [0.8, 1.34, 1.57]
third_puck_zone: [1, 1.34, 1.57]
forth_puck: [0.6, 1.34, 1.57]
fifth_puck: [0.6, 1.34, 1.57]

# Orange zone
# red_cell_puck: [2.5, 0.45]
# green_cell_puck: [2.5, 0.75]
# blue_cell_puck: [2.5, 1.05]
# blunium_start_push_pos:
# blunium_finish_push_pos:
# blunium_acc: [1.32, 0.2]
# accelerator_unloading_pos:
# goldenium_grab_pos:
# scales_unloading_pos: [1.65, 1.48, 3.65]  # for secondary robot
# scales_goldenium_pos: [1.65, 1.48, 0]  # FIXME

# Purple zone
red_cell_puck: [0.5, 0.45]
green_cell_puck: [0.5, 0.75]
blue_cell_puck: [0.5, 1.05]
blunium_start_push_pos:
blunium_finish_push_pos:
blunium_acc: [1.72, 0.2]
accelerator_unloading_pos:
goldenium_grab_pos:
scales_unloading_pos: [1.34, 1.48, 3.65]  # for secondary robot
scales_goldenium_pos: [1.34, 1.48, 0]  # FIXME
