secondary_robot:
  purple_side:
    first_puck_zone: [0.22, 1.81, 1.57]
    second_puck_zone: [0.12, 1.81, 1.57]
    third_puck_zone: [0.585, 1.34, 1.57]
    forth_puck_zone: [0.785, 1.34, 1.57]
    fifth_puck_zone: [0.985, 1.34, 1.57]
    scales_zone: [1.34, 1.5, 3.65]
    sixth_puck_zone: [0.885, 1.35, 1.57]
    seven_puck_zone: [0.685, 1.35, 1.57]
    eight_puck_zone: [0.485, 1.35, 1.57]
    nine_puck_zone: [0.32, 1.82, 1.57]
    start_zone: [0.23, 0.84, 0]


  yellow_side:
    first_puck_zone: [2.78, 1.82, 1.57]
    second_puck_zone: [2.88, 1.82, 1.57]
    third_puck_zone: [2.415, 1.35, 1.57]
    forth_puck_zone: [2.215, 1.35, 1.57]
    fifth_puck_zone: [2.015, 1.35, 1.57]
    scales_zone: [1.65, 1.5, 3.65]
    six_puck_zone: [2.115, 1.35, 1.57]
    seven_puck_zone: [2.315, 1.35, 1.57]
    eight_puck_zone: [2.15, 1.35, 1.57]
    nine_puck_zone: [2.68, 1.82, 1.57]
    start_zone: [2.77, 0.84, 3.14]

#FIXME::CHANGE ZONE TO SIDE
yellow_zone:
  start_zone: [2.82, 0.45, 3.14]
  red_cell_puck: [2.5, 0.45]
  green_cell_puck: [2.5, 0.75]
  blue_cell_puck: [2.5, 1.05]

  blunium_collect_PREpos: [1.29, 0.45, -1.57]
  blunium_collect_pos: [1.29, 0.23, -1.57]

  accelerator_PREunloading_pos: [1.14, 0.2, 0.525]
  accelerator_unloading_pos_far: [1.11, 0.16, 0.525]
  accelerator_unloading_pos: [1.11, 0.125, 0.525]  # for main
  goldenium_PREgrab_pos: [0.9, 0.45, -1.57]
  goldenium_grab_pos: [0.78, 0.24, -1.57]  # for main
  scales_goldenium_PREpos: [1.8, 1.05, 1.4]  # for main
  scales_goldenium_pos: [1.72, 1.4, 1.9]  # for main

#FIXME::CHANGE ZONE TO SIDE
# can be reached using rospy.get_param("purple_zone/red_cell_puck"
purple_zone:
  start_zone: [0.28, 0.45, 0]
  red_cell_puck: [0.5, 0.45]
  green_cell_puck: [0.5, 0.75]
  blue_cell_puck: [0.5, 1.05]

  blunium_collect_PREpos: [1.72, 0.45, -1.57]
  blunium_collect_pos: [1.72, 0.25, -1.57]

  accelerator_PREunloading_pos: [1.86, 0.2, 0.525]
  accelerator_unloading_pos_far: [1.86, 0.16, 0.525]
  accelerator_unloading_pos: [1.86, 0.125, 0.525]  # for main
  goldenium_PREgrab_pos: [2.1, 0.45, -1.57]
  goldenium_grab_pos: [2.25, 0.24, -1.57]  # for main
  scales_goldenium_PREpos: [1.34, 1.05, 1.4]  # for main
  scales_goldenium_pos: [1.34, 1.4, 1.4]  # for main  # FIXME
