secondary_robot:
  purple_side:
    first_puck_zone: [0.225, 1.81, 1.57]
    second_puck_zone: [0.125, 1.81, 1.57]
    third_puck_zone: [0.6, 1.36, 1.57]
    forth_puck_zone: [0.8, 1.36, 1.57]
    fifth_puck_zone: [1.0, 1.36, 1.57]
    scales_zone: [1.35, 1.48, 3.65]
    sixth_puck_zone: [0.9, 1.36, 1.57]
    seventh_puck_zone: [0.7, 1.36, 1.57]
    eighth_puck_zone: [0.5, 1.36, 1.57]
    nineth_puck_zone: [0.325, 1.81, 1.57]
    start_zone: [0.2, 0.75, 0.]
    redium_zone_center: [0.275, 0.45, -1.57]
    redium_zone_first: [0.22, 0.35, 3.14]
    redium_zone_second: [0.22, 0.43, 3.14]
    redium_zone_third: [0.22, 0.51, 3.14]
    redium_zone_forth: [0.15, 0.75, -1.57]
    reflected_last_zone : [0.21, 0.36, -1.7]

  yellow_side:
    first_puck_zone: [2.775, 1.81, 1.57]
    second_puck_zone: [2.875, 1.81, 1.57]
    third_puck_zone: [2.4, 1.36, 1.57]
    forth_puck_zone: [2.2, 1.36, 1.57]
    fifth_puck_zone: [2.0, 1.36, 1.57]
    scales_zone: [1.66, 1.49, 3.65]
    sixth_puck_zone: [2.1, 1.36, 1.57]
    seventh_puck_zone: [2.3, 1.36, 1.57]
    eighth_puck_zone: [2.5,  1.36, 1.57]
    nineth_puck_zone: [2.675, 1.81, 1.57]
    start_zone: [2.80, 0.75, 3.14]
    redium_zone_center: [2.725, 0.45, -1.57]
    redium_zone_first: [2.85, 0.65, -1.57]
    redium_zone_second: [2.75, 0.65, -1.57]
    redium_zone_third: [2.75, 0.75, -1.5]
    redium_zone_forth: [2.85, 0.75, -1.57]
    reflected_last_zone : [2.79, 0.45, 1.44]

ground_spacing_dist: 0.3  # between pucks on ground
chaos_radius: 0.15

# lab table
main_robot:
  yellow_side:
    red_cell_puck: [2.51, 0.45]
    blunium: [1.29, 0.025]  # outer side of the puck
    scales_area: [[1.4, 1], [1.4, 1.6], [2.3, 1.6], [2.3, 1.]]
    yellow_cells_area: [[2.4, 0.3], [2.4, 1.2], [2.7, 1.2], [2.7, 0.3]]
    goldenium: [0.77, 0.05]  # outer side of the puck
    chaos_center: [2.01, 1.05]
    area_to_search_chaos: [[2.3, 0.6], [1.7, 0.6], [1.7, 1.25], [2.3, 1.25]]

  purple_side:
    red_cell_puck: [0.5, 0.45]
    blunium: [1.71, 0.025]  # outer side of the puck
    scales_area: [[1.4, 1.2], [1.4, 1.6], [0.7, 1.6], [0.7, 1.2]]
    purple_cells_area: [[0.4, 0.3], [0.4, 1.2], [0.7, 1.2], [0.7, 0.3]]
    goldenium: [2.22, 0.05]  # outer side of the puck
    chaos_center: [1, 1.05]
    area_to_search_chaos: [[0.7, 0.6], [1.3, 0.6], [1.3, 1.25], [0.7, 1.25]]

# sber table
# main_robot:
#   yellow_side:
#     red_cell_puck: [2.5, 0.45]
#     blunium: [1.3, 0.025]  # outer side of the puck
#     scales_area: [[1.4, 1], [1.4, 1.6], [2.3, 1.6], [2.3, 1.]]
#     yellow_cells_area: [[2.4, 0.3], [2.4, 1.2], [2.7, 1.2], [2.7, 0.3]]
#     goldenium: [0.775, 0.05]  # outer side of the puck
#     chaos_center: [2.00, 1.05]
#     area_to_search_chaos: [[2.3, 0.6], [1.7, 0.6], [1.7, 1.25], [2.3, 1.25]]

#   purple_side:
#     red_cell_puck: [0.5, 0.45]
#     blunium: [1.715, 0.025]  # outer side of the puck
#     scales_area: [[1.4, 1.2], [1.4, 1.6], [0.7, 1.6], [0.7, 1.2]]
#     purple_cells_area: [[0.4, 0.3], [0.4, 1.2], [0.7, 1.2], [0.7, 0.3]]
#     goldenium: [2.235, 0.05]  # outer side of the puck
#     chaos_center: [1, 1.05]
#     area_to_search_chaos: [[0.7, 0.6], [1.3, 0.6], [1.3, 1.25], [0.7, 1.25]]

# trener
# yellow_side:
#   red_cell_puck: [2.495, 0.445]
#   blunium: [1.285, 0.03]  # outer side of the puck
#   scales_area: [[1.4, 1], [1.4, 1.6], [2.3, 1.6], [2.3, 1.]]
#   goldenium: [0.78, 0.05]  # outer side of the puck
#   chaos_center: [2.0, 1.05]

# purple_side:
#   red_cell_puck: [0.505, 0.445]
#   blunium: [1.72, 0.03]  # outer side of the puck
#   scales_area: [[1.4, 1.2], [1.4, 1.6], [0.7, 1.6], [0.7, 1.2]]
#   goldenium: [2.23, 0.05]  # outer side of the puck
#   chaos_center: [1, 1.05]

# left
# yellow_side:
#   red_cell_puck: [2.495, 0.445]
#   blunium: [1.295, 0.03]  # outer side of the puck
#   scales_area: [[1.4, 1], [1.4, 1.6], [2.3, 1.6], [2.3, 1.]]
#   goldenium: [0.775, 0.05]  # outer side of the puck
#   chaos_center: [2.0, 1.05]

# purple_side:
#   red_cell_puck: [0.50, 0.445]
#   blunium: [1.71, 0.03]  # outer side of the puck
#   scales_area: [[1.4, 1.2], [1.4, 1.6], [0.7, 1.6], [0.7, 1.2]]
#   goldenium: [2.22, 0.05]  # outer side of the puck
#   chaos_center: [1, 1.05]

