robot_name: "main_robot"
start_side: "yellow"

critical_angle: 2.094
# approach_dist: 0.123  # chaos and table pucks, from center o frobot to center of puck  TRUE
horiz_pucks_approach_dist: 0.115  # WITH OFFSET
vertical_pucks_approach_dist: 0.185
robot_outer_radius: 0.165  # FIXME
drive_back_dist: 0.09
RATE: 10
scale_factor: 10
coords_threshold: 0.01
stick_len: 0.03
