velocity_vector: [0.6, 0.6, 1.5]
robot_name: "main_robot"
num_points_in_path: 100
robot_radius: 0.1
k_linear_wp: 1.2
k_linear_vp: 1.2
k : 0.07
min_dist_to_goal_point: 0.2  # 0.1
# max rate of the planner
RATE: 15
# goal tolerance
XY_GOAL_TOLERANCE: 0.01
YAW_GOAL_TOLERANCE: 0.007
# maximum speed
V_MAX: 0.5
W_MAX: 1.5
AV_MAX: 1
AW_MAX: 0.8
# acceleration at beginning of movements
ACCELERATION: 1.0
# goal distance for deceleration
D_DECELERATION: 0.15
R_DECELERATION: 1
exp_const: 0.03
# power of deceleration factor
GAMMA: 0.75
# params for accurate movements to water towers or cube heaps
XY_ACCURATE_GOAL_TOLERANCE: 0.005
YAW_ACCURATE_GOAL_TOLERANCE: 0.05
D_ACCURATE_DECELERATION: 0.20
NUM_RANGEFINDERS: 16
COLLISION_STOP_DISTANCE: 150
COLLISION_STOP_NEIGHBOUR_DISTANCE: 50
COLLISION_GAMMA: 2
collision:
    min_dist_to_obstacle_lidar: 0.5
    min_dist_to_obstacle_sensor: 0.18
    sensor_position: [[-0.122, -0.05959, 2.0944], [0.0327, 0.14795, 2.0944], [-0.1643, 0., 3.1415], [0.01315, -0.13807, 4.19],
[-0.13415, -0.05303, 4.19], [0.105, 0.07032, 0.], [0.092,-0.0825, 0. ]]
    angle_sensor: 0.261799

